
name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Quarkus Native Image
        run: mvn clean package -Pnative -Dquarkus.native.container-build=true
      -
        name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          platforms: linux/arm64
          push: true
          file: "./src/main/docker/Dockerfile.native-micro"
          tags: dahool/qtcompanion-arm:latest