
name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
      -
        name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'mandrel'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: corepack enable
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Quarkus Native Image
        run: mvn clean package -Pnative
      -
        name: Build and Push Docker Image
        run: docker buildx build --platform linux/amd64 -f src/main/docker/Dockerfile.native-micro -t ${{ secrets.DOCKERHUB_USERNAME }}/qtcompanion:latest . --push